plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "gemfiles/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Metrics
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "eussiror.gemspec"
    - "Appraisals"

Metrics/MethodLength:
  Max: 20

# RSpec
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

# Enforce spy pattern: allow in setup, have_received in expectation
RSpec/MessageSpies:
  EnforcedStyle: have_received

# Merge multiple allow(...).to receive into receive_messages
RSpec/ReceiveMessages:
  Enabled: true

# Rails
Rails/NegateInclude:
  Enabled: false

Rails/Output:
  Exclude:
    - "lib/eussiror/error_reporter.rb"

# Avoid regexp when a plain string argument is sufficient
Style/RedundantRegexpArgument:
  Enabled: true

# Use %r{} for regexp literals containing forward slashes
Style/RegexpLiteral:
  EnforcedStyle: mixed
